// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixOptionsTest {
    internal sealed partial class Vsix {
        public const string Id = "VsixOptionsTest.ed7d2271-e544-4d8f-82d7-b689a730ec99";
        public const string Name = "VsixOptionsTest";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "reduckted";
        public const string Tags = "";
    }
}
