// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace VsixOptionsTest {
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids {
        public const string VsixOptionsTestString = "4b97f03d-333d-4acf-9244-42a23309c2af";
        public static Guid VsixOptionsTest = new Guid(VsixOptionsTestString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds {
    }
}